language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- git clone https://github.com/okadome-LAB/test_ubiquitous.git
- cd test_ubiquitous
script:
- pytest 
notifications:
  email:
  - your@mail